import fs from 'fs';

// Known exact mappings for films to guarantee zero ambiguity
export const CURATED_FILM_DATA = {
  'machine': {
    imdb: 'tt27718012',
    allocine: '32007',
    isSeries: true,
    trailerQuery: 'Machine Série Arte Bande Annonce',
  },
  'gtmax': {
    imdb: 'tt29342795',
    allocine: '322495',
    isSeries: false,
    trailerQuery: 'GTMAX Bande Annonce VF Netflix',
  },
  'furies': {
    imdb: 'tt23730594',
    allocine: '31317',
    isSeries: true,
    trailerQuery: 'Furies Bande Annonce Netflix',
  },
  'fiasco': {
    imdb: 'tt27299066',
    allocine: '31477',
    isSeries: true,
    trailerQuery: 'Fiasco Série Netflix Pierre Niney Bande Annonce',
  },
  'le-salaire-de-la-peur': {
    imdb: 'tt27488094',
    allocine: '315182',
    isSeries: false,
    trailerQuery: 'Le Salaire de la Peur 2024 Netflix Bande Annonce',
  },
  'monte-cristo': {
    imdb: 'tt26446278',
    allocine: '288404',
    isSeries: false,
    trailerQuery: 'Le Comte de Monte-Cristo Bande Annonce Pierre Niney',
  },
  'the-killer': {
    imdb: 'tt2552882',
    allocine: '131724',
    isSeries: false,
    trailerQuery: 'The Killer 2024 John Woo Trailer',
  },
  'largo-winch-3': {
    imdb: 'tt23049322',
    allocine: '210439',
    isSeries: false,
    trailerQuery: 'Largo Winch Le Prix de l argent Bande Annonce',
  },
  'sous-la-seine': {
    imdb: 'tt13964390',
    allocine: '313341',
    isSeries: false,
    trailerQuery: 'Sous la Seine Bande Annonce Netflix',
  },
  'lamour-ouf': {
    imdb: 'tt27490099',
    allocine: '221617',
    isSeries: false,
    trailerQuery: 'L Amour Ouf Bande Annonce Gilles Lellouche',
  },
  'elyas': {
    imdb: 'tt28336131',
    allocine: '317127',
    isSeries: false,
    trailerQuery: 'Elyas Bande Annonce Roschdy Zem',
  },
  'the-substance': {
    imdb: 'tt17526714',
    allocine: '300680',
    isSeries: false,
    trailerQuery: 'The Substance Bande Annonce Demi Moore',
  },
  'alibi-com-2': {
    imdb: 'tt17072938',
    allocine: '298950',
    isSeries: false,
    trailerQuery: 'Alibi.com 2 Bande Annonce',
  },
  'john-wick-4': {
    imdb: 'tt10366206',
    allocine: '274387',
    isSeries: false,
    trailerQuery: 'John Wick 4 Bande Annonce VF',
  },
  'murder-mystery-2': {
    imdb: 'tt15295770',
    allocine: '277491',
    isSeries: false,
    trailerQuery: 'Murder Mystery 2 Bande Annonce Netflix',
  },
  'uncharted': {
    imdb: 'tt1464335',
    allocine: '184989',
    isSeries: false,
    trailerQuery: 'Uncharted Bande Annonce VF Tom Holland',
  },
  'goliath': {
    imdb: 'tt11928096',
    allocine: '273618',
    isSeries: false,
    trailerQuery: 'Goliath Bande Annonce Pierre Niney',
  },
  'wednesday-mercredi': {
    imdb: 'tt13443470',
    allocine: '27878',
    isSeries: true,
    trailerQuery: 'Mercredi Série Netflix Bande Annonce VF',
  },
  'the-355': {
    imdb: 'tt8356942',
    allocine: '264560',
    isSeries: false,
    trailerQuery: 'The 355 Bande Annonce VF',
  },
  'bac-nord': {
    imdb: 'tt10404944',
    allocine: '274530',
    isSeries: false,
    trailerQuery: 'Bac Nord Bande Annonce VF',
  },
  'black-widow': {
    imdb: 'tt3480822',
    allocine: '197998',
    isSeries: false,
    trailerQuery: 'Black Widow Bande Annonce VF',
  },
  'lupin': {
    imdb: 'tt2531336',
    allocine: '24118',
    isSeries: true,
    trailerQuery: 'Lupin Bande Annonce Netflix Omar Sy',
  },
  'sentinelle': {
    imdb: 'tt11734264',
    allocine: '279090',
    isSeries: false,
    trailerQuery: 'Sentinelle 2021 Netflix Bande Annonce Olga Kurylenko',
  },
  'family-business': {
    imdb: 'tt9215096',
    allocine: '24564',
    isSeries: true,
    trailerQuery: 'Family Business Netflix Bande Annonce',
  },
  'stillwater': {
    imdb: 'tt10633456',
    allocine: '275704',
    isSeries: false,
    trailerQuery: 'Stillwater Bande Annonce VF Matt Damon',
  },
  'dune': {
    imdb: 'tt1160419',
    allocine: '252643',
    isSeries: false,
    trailerQuery: 'Dune Bande Annonce VF Denis Villeneuve',
  },
  'braqueurs': {
    imdb: 'tt13300584',
    allocine: '27473',
    isSeries: true,
    trailerQuery: 'Braqueurs La Série Netflix Bande Annonce',
  },
  '30-jours-max': {
    imdb: 'tt11261314',
    allocine: '277433',
    isSeries: false,
    trailerQuery: '30 Jours Max Bande Annonce',
  },
  'balle-perdue': {
    imdb: 'tt11855660',
    allocine: '271813',
    isSeries: false,
    trailerQuery: 'Balle Perdue Bande Annonce Netflix Alban Lenoir',
  },
  'bronx': {
    imdb: 'tt10442742',
    allocine: '274483',
    isSeries: false,
    trailerQuery: 'Bronx Bande Annonce Olivier Marchal Netflix',
  },
  'police': {
    imdb: 'tt9404284',
    allocine: '269894',
    isSeries: false,
    trailerQuery: 'Police Film Anne Fontaine Bande Annonce Omar Sy',
  },
  'mortel': {
    imdb: 'tt8268484',
    allocine: '23528',
    isSeries: true,
    trailerQuery: 'Mortel Série Netflix Bande Annonce',
  },
  '6-underground': {
    imdb: 'tt8106534',
    allocine: '263158',
    isSeries: false,
    trailerQuery: '6 Underground Bande Annonce VF Michael Bay',
  },
  'les-miserables': {
    imdb: 'tt10199590',
    allocine: '268406',
    isSeries: false,
    trailerQuery: 'Les Misérables Bande Annonce Ladj Ly',
  },
  'nicky-larson': {
    imdb: 'tt7146608',
    allocine: '257604',
    isSeries: false,
    trailerQuery: 'Nicky Larson et le Parfum de Cupidon Bande Annonce',
  },
  'mission-impossible-fallout': {
    imdb: 'tt4649466',
    allocine: '239857',
    isSeries: false,
    trailerQuery: 'Mission Impossible Fallout Bande Annonce VF',
  },
  'overdrive': {
    imdb: 'tt1995150',
    allocine: '193796',
    isSeries: false,
    trailerQuery: 'Overdrive Bande Annonce VF Scott Eastwood',
  },
  'dunkirk': {
    imdb: 'tt5013056',
    allocine: '240850',
    isSeries: false,
    trailerQuery: 'Dunkerque Bande Annonce VF Christopher Nolan',
  },
  'valerian': {
    imdb: 'tt2239822',
    allocine: '237821',
    isSeries: false,
    trailerQuery: 'Valerian et la Cité des mille planètes Bande Annonce VF',
  },
  'alibi-com': {
    imdb: 'tt5814534',
    allocine: '244833',
    isSeries: false,
    trailerQuery: 'Alibi.com Bande Annonce Philippe Lacheau',
  },
  'raid-dingue': {
    imdb: 'tt5442742',
    allocine: '244670',
    isSeries: false,
    trailerQuery: 'Raid Dingue Bande Annonce Dany Boon',
  },
  'jason-bourne': {
    imdb: 'tt4196776',
    allocine: '231367',
    isSeries: false,
    trailerQuery: 'Jason Bourne Bande Annonce VF Matt Damon',
  },
  'bastille-day': {
    imdb: 'tt2368619',
    allocine: '215286',
    isSeries: false,
    trailerQuery: 'Bastille Day Bande Annonce VF Idris Elba',
  },
  'taken-3': {
    imdb: 'tt2446042',
    allocine: '213453',
    isSeries: false,
    trailerQuery: 'Taken 3 Bande Annonce VF Liam Neeson',
  },
  'james-bond-spectre': {
    imdb: 'tt2379713',
    allocine: '206892',
    isSeries: false,
    trailerQuery: '007 Spectre Bande Annonce VF',
  },
  'le-transporteur-heritage': {
    imdb: 'tt2938956',
    allocine: '219462',
    isSeries: false,
    trailerQuery: 'Le Transporteur Heritage Bande Annonce VF',
  },
  'l-affaire-sk1': {
    imdb: 'tt3392576',
    allocine: '224795',
    isSeries: false,
    trailerQuery: 'L Affaire SK1 Bande Annonce',
  },
  '3-days-to-kill': {
    imdb: 'tt2172934',
    allocine: '208358',
    isSeries: false,
    trailerQuery: '3 Days to Kill Bande Annonce VF Kevin Costner',
  },
  'the-hunger-games': {
    imdb: 'tt1951265',
    allocine: '200088',
    isSeries: false,
    trailerQuery: 'Hunger Games La Revolte Partie 1 Bande Annonce VF',
  },
  'lucy': {
    imdb: 'tt2872732',
    allocine: '186452',
    isSeries: false,
    trailerQuery: 'Lucy Bande Annonce VF Luc Besson',
  },
  'fast-furious-6': {
    imdb: 'tt1905041',
    allocine: '189651',
    isSeries: false,
    trailerQuery: 'Fast and Furious 6 Bande Annonce VF',
  },
  'malavita': {
    imdb: 'tt2404311',
    allocine: '207825',
    isSeries: false,
    trailerQuery: 'Malavita Bande Annonce VF Luc Besson Robert De Niro',
  },
  'de-l-autre-cote-du-periph': {
    imdb: 'tt2215286',
    allocine: '190911',
    isSeries: false,
    trailerQuery: 'De l autre côté du périph Bande Annonce Omar Sy',
  },
  'taken-2': {
    imdb: 'tt1397280',
    allocine: '187841',
    isSeries: false,
    trailerQuery: 'Taken 2 Bande Annonce VF Liam Neeson',
  },
  'from-paris-with-love': {
    imdb: 'tt1179040',
    allocine: '135547',
    isSeries: false,
    trailerQuery: 'From Paris with Love Bande Annonce VF John Travolta',
  },
  'un-prophete': {
    imdb: 'tt1229238',
    allocine: '125866',
    isSeries: false,
    trailerQuery: 'Un Prophète Bande Annonce Jacques Audiard',
  },
  'banlieue-13-ultimatum': {
    imdb: 'tt1247640',
    allocine: '134188',
    isSeries: false,
    trailerQuery: 'Banlieue 13 Ultimatum Bande Annonce',
  },
  'babylon-a-d': {
    imdb: 'tt0364970',
    allocine: '58941',
    isSeries: false,
    trailerQuery: 'Babylon A.D. Bande Annonce Vin Diesel',
  },
  'largo-winch': {
    imdb: 'tt0808339',
    allocine: '124948',
    isSeries: false,
    trailerQuery: 'Largo Winch 1 Bande Annonce Tomer Sisley',
  },
  'mesrine-l-ennemi-public-n-1': {
    imdb: 'tt0411272',
    allocine: '111809',
    isSeries: false,
    trailerQuery: 'Mesrine L Ennemi Public N 1 Bande Annonce Vincent Cassel',
  },
  'taxi-4': {
    imdb: 'tt0804540',
    allocine: '110681',
    isSeries: false,
    trailerQuery: 'Taxi 4 Bande Annonce VF',
  },
  'danny-the-dog': {
    imdb: 'tt0342258',
    allocine: '52538',
    isSeries: false,
    trailerQuery: 'Danny the Dog Bande Annonce Jet Li',
  },
  'yamakasi': {
    imdb: 'tt0267129',
    allocine: '29366',
    isSeries: false,
    trailerQuery: 'Yamakasi Les Samouraïs des temps modernes Bande Annonce',
  },
};
